// AutomatikPOST — Page configuration
// Used by the router in App.jsx

export const PAGE_TITLES = {
  dashboard: 'Dashboard',
  posts: 'Posts',
  create: 'Criar Post',
  ai: 'Produtor IA',
  automations: 'Automações',
  wordpress: 'Sites WordPress',
  performance: 'Performance',
  productivity: 'Produtividade da Equipe',
  projects: 'Projetos Kanban',
  templates: 'Templates',
  sources: 'Fontes',
  calendar: 'Calendário',
  settings: 'Configurações',
  users: 'Usuários',
  media: 'Biblioteca de Mídia',
  backup: 'Backup & Restauração',
  reports: 'Relatórios',
  competitors: 'Monitor de Concorrentes',
  webstories: 'Web Stories',
  ideas: 'Gerador de Ideias',
  editor: 'Editor de Post',
  postanalytics: 'Analytics do Post',
  tags: 'Tags & Categorias',
  publishhistory: 'Histórico de Publicações',
  recurring: 'Cronogramas Recorrentes',
  support: 'Central de Suporte',
  integrations: 'Integrações',
  seodeep: 'SEO Profundo',
  abtest: 'Testes A/B',
  contentbrief: 'Content Brief',
  health: 'System Health',
  admin: 'Painel Administrativo',
  repurpose: 'Repurposing de Conteúdo',
  contentgap: 'Analisador de Gaps',
  evergreen: 'Conteúdo Evergreen',
  readability: 'Análise de Legibilidade',
  plagiarism: 'Verificador de Plágio',
  exportreports: 'Exportar Relatórios',
  notifications: 'Central de Notificações',
  multichannel: 'Publicação Multicanal',
};
